spring.application.name=demo02
server.port = 8884
logging.file.name = demo02.log
spring.datasource.url=jdbc:postgresql://postgres:5432/demo02
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
